server:
  port: 8083

spring:
    datasource:
        url: jdbc:postgresql://127.0.0.1:5432/gmail-demo
        username: postgres
        password: postgres
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
        javax:
          persistence:
            schema-generation:
              create-source: metadata
              scripts:
                action: create
                create-target: create.sql
      open-in-view: true
    web:
      locale: pt_BR
    main:
      allow-bean-definition-overriding: true
    thymeleaf:
      cache: false
      enabled: true
      prefix: classpath:/templates/
      suffix: .html
custom:
  clientId: ${clientId:123}
  clientSecret: ${clientSecret:123}